// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-sphere/sphere-bun-layout/internal/biz/task"
	"github.com/go-sphere/sphere-bun-layout/internal/config"
	"github.com/go-sphere/sphere-bun-layout/internal/pkg/database"
	api2 "github.com/go-sphere/sphere-bun-layout/internal/server/api"
	"github.com/go-sphere/sphere-bun-layout/internal/service/api"
	"github.com/go-sphere/sphere/core/boot"
)

// Injectors from wire.go:

func NewApplication(conf *config.Config) (*boot.Application, error) {
	apiConfig := conf.API
	databaseConfig := conf.Database
	db, err := database.NewDbConnection(databaseConfig)
	if err != nil {
		return nil, err
	}
	bunDB, err := database.NewDatabase(db)
	if err != nil {
		return nil, err
	}
	service := api.NewService(bunDB)
	web := api2.NewWebServer(apiConfig, service)
	dbInit := task.NewDbInit(bunDB)
	application := newApplication(web, dbInit)
	return application, nil
}
